-- Run this in the Supabase SQL Editor.

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 40),
  message text not null check (char_length(message) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

drop policy if exists "Anyone can read messages" on public.messages;
create policy "Anyone can read messages"
on public.messages
for select
to anon
using (true);

drop policy if exists "Anyone can post messages" on public.messages;
create policy "Anyone can post messages"
on public.messages
for insert
to anon
with check (
  char_length(name) between 1 and 40
  and char_length(message) between 1 and 500
);

-- Add the table to Supabase Realtime if it is not already included.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'messages'
  ) then
    alter publication supabase_realtime add table public.messages;
  end if;
end $$;
